# Generated by Django 5.0 on 2023-12-20 19:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.ImageField(upload_to="images/")),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_id",
                    models.CharField(
                        choices=[("tooth", "Tooth"), ("caries", "Caries")],
                        max_length=100,
                    ),
                ),
                ("start_x", models.IntegerField()),
                ("start_y", models.IntegerField()),
                ("end_x", models.IntegerField()),
                ("end_y", models.IntegerField()),
                ("confirmed", models.BooleanField(default=False)),
                ("confidence_percent", models.FloatField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "surface",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.image"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
