# Generated by Django 5.0 on 2023-12-20 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="annotation",
            table="annotations",
        ),
        migrations.AlterModelTable(
            name="image",
            table="images",
        ),
    ]
