# Generated by Django 5.0 on 2023-12-20 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_annotation_id_alter_image_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="path",
            new_name="image",
        ),
    ]
