# Generated by Django 5.0 on 2023-12-21 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_annotation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="image",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.image"
            ),
        ),
    ]
